image: fedora/latest
repositories:
  mongodb-org-4.4: https://repo.mongodb.org/yum/redhat/8/mongodb-org/4.4/x86_64
packages:
  - go
  - mongodb-org
sources:
    - https://git.sr.ht/~ernie/goeverywhere-go
tasks:
    - build: |
        cd goeverywhere-go
        go build
    - vet: |
        cd goeverywhere-go
        go vet
    - test: |
        cd goeverywhere-go
        sudo systemctl start mongod
        ./scripts/setup_empty_db.sh
        go test -v
