image: fedora/latest
packages:
  - go
sources:
    - https://git.sr.ht/~ernie/goeverywhere-go
tasks:
    - setup: |
        sudo dnf install -y 'dnf-command(config-manager)'
        sudo dnf config-manager --add-repo https://repo.mongodb.org/yum/redhat/8/mongodb-org/4.4/x86_64
        curl -LO https://www.mongodb.org/static/pgp/server-4.4.asc
        sudo rpm --import server-4.4.asc
        sudo dnf install -y mongodb-org
        sudo systemctl start mongod
    - build: |
        cd goeverywhere-go
        go build
    - vet: |
        cd goeverywhere-go
        go vet
    - test: |
        cd goeverywhere-go
        ./scripts/setup_empty_db.sh
        go test -v
