image: fedora/latest
environment:
  - goversion: 1.15.8
  - reponame: goeverywhere-go
sources:
    - https://git.sr.ht/~ernie/goeverywhere-go
tasks:
    - setup-mongo: |
        sudo dnf install -y 'dnf-command(config-manager)'
        sudo dnf config-manager --add-repo https://repo.mongodb.org/yum/redhat/8/mongodb-org/4.4/x86_64
        curl -LO https://www.mongodb.org/static/pgp/server-4.4.asc
        sudo rpm --import server-4.4.asc
        sudo dnf install -y mongodb-org
        sudo systemctl start mongod
    - setup-golang: |
        curl -LO https://golang.org/dl/go${goversion}.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go${goversion}.linux-amd64.tar.gz
        sudo ln -s /usr/local/go/bin/* /usr/local/bin/
    - build: |
        cd ${reponame}
        go build
    - vet: |
        cd ${reponame}
        go vet
    - test: |
        cd ${reponame}
        ./scripts/setup_empty_db.sh
        go test -v
triggers:
  - action: email
    condition: always
    to: Ernie Hershey <builds.sr.ht@ernie.org>
