printjson(db.gps_log.ensureIndex({ entry_date: 1, entry_source: 1, accuracy: 1 }, { unique: true, dropDups: true }))
printjson(db.gps_log.ensureIndex( { loc : "2dsphere" } ))
printjson(db.gps_log.ensureIndex({ entry_source: 1 }))
printjson(db.nodes.ensureIndex(   {  loc: '2dsphere' } ))
printjson(db.nodes.ensureIndex( { external_id: 1 },  { unique: true }))
